import pandas as pd
import argparse

# ----------------------------------------------------------
# Define the 20 fields in order exactly as they appear in SQL
# ----------------------------------------------------------
# FIELDS = [
#     "block_time",
#     "block_number",
#     "tx_hash",
#     "tx_from_address",
#     "tx_to_address",
#     "gas_used",
#     "tx_fee_eth",
#     "timeboosted",
#     "bought_token_symbol",
#     "sold_token_symbol",
#     "bought_token_amount",
#     "sold_token_amount",
#     "amount_usd",
#     "auction_round",
#     "winner_address",
#     "winner_name",
#     "top_bid_eth",
#     "paid_bid_eth",
#     "express_lane_controller_address"
# ]
FIELDS = [
    "block_time",
    "block_number",
    "tx_hash",
    "tx_from_address",
    "tx_to_address",
    "success",
    "gas_used",
    "gas_price",
    "tx_fee_eth",
    "timeboosted",
]

def parse_merged(row):
    """
    Split merged string into all fields.
    Handles missing fields gracefully.
    """
    parts = [p.strip() for p in row.split("|")]

    # If there are fewer parts than fields, pad with empty strings
    if len(parts) < len(FIELDS):
        parts += [""] * (len(FIELDS) - len(parts))

    return pd.Series(parts[:len(FIELDS)], index=FIELDS)


def main(input_file, output_file):
    print(f"Loading merged dataset from: {input_file}")
    df = pd.read_csv(input_file)

    if "merged" not in df.columns:
        raise ValueError("Input CSV must contain a 'merged' column generated by Dune.")

    print("Parsing merged field...")
    parsed = df["merged"].apply(parse_merged)

    print("Combining original + parsed fields...")
    out = pd.concat([df, parsed], axis=1)

    out = out.drop(columns=["merged"])

    # Convert numeric fields
    numeric_fields = [
        "gas_used", "tx_fee_eth", "bought_token_amount",
        "sold_token_amount", "amount_usd",
        "auction_round", "top_bid_eth", "paid_bid_eth"
    ]

    for col in numeric_fields:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")

    # Convert block_time
    out["block_time"] = pd.to_datetime(out["block_time"], errors="coerce")

    print(f"Saving parsed dataset to: {output_file}")
    out.to_csv(output_file, index=False)
    print("Done.")


if __name__ == "__main__":
    # parser = argparse.ArgumentParser(description="Parse merged Timeboost Dune export.")
    # parser.add_argument("input_file", help="Path to input CSV with merged column")
    # parser.add_argument("output_file", help="Path to output cleaned CSV")
    # args = parser.parse_args()
    input_file = "data/reverts/august/01KB09SQGF99VHRDT0HHHK9AWZ.csv"
    output_file = "data/reverts/august/01KB09SQGF99VHRDT0HHHK9AWZ_parsed.csv"
    main(input_file, output_file)
