"""
Parse merged-column Dune exports into clean CSVs.

Usage:
    python parse_csv.py txs   INPUT_FILE [OUTPUT_FILE]
    python parse_csv.py reverts INPUT_FILE [OUTPUT_FILE]

If OUTPUT_FILE is omitted, appends '_parsed' before the extension.
"""

import argparse
import os
import pandas as pd

# ── Schema definitions ──────────────────────────────────────
SCHEMAS = {
    "txs": {
        # "fields": [
        #     "block_time", "block_number", "tx_hash",
        #     "tx_from_address", "tx_to_address",
        #     "gas_used", "tx_fee_eth", "timeboosted",
        #     "bought_token_symbol", "sold_token_symbol",
        #     "bought_token_amount", "sold_token_amount", "amount_usd",
        # ],
                "fields": [
            "block_time", "block_number", "tx_hash",
            "tx_from_address", "tx_to_address",
            "bought_token_symbol", "sold_token_symbol",
            "bought_token_amount", "sold_token_amount", "amount_usd",
        ],
        "numeric": [
            "gas_used", "tx_fee_eth",
            "bought_token_amount", "sold_token_amount", "amount_usd",
        ],
    },
    "reverts": {
        "fields": [
            "block_time", "block_number", "tx_hash",
            "tx_from_address", "tx_to_address",
            "success", "gas_used", "gas_price",
            "tx_fee_eth", "timeboosted",
        ],
        "numeric": [
            "gas_used", "gas_price", "tx_fee_eth",
        ],
    },
}


def parse_merged(input_file, output_file, schema_name):
    schema = SCHEMAS[schema_name]
    fields = schema["fields"]
    n_fields = len(fields)

    print(f"[{schema_name}] Loading: {input_file}")
    df = pd.read_csv(input_file)

    if "merged" not in df.columns:
        raise ValueError("Input CSV must contain a 'merged' column generated by Dune.")

    # Vectorised split — orders of magnitude faster than .apply() row-by-row
    print(f"[{schema_name}] Parsing {len(df):,} rows ({n_fields} fields)...")
    split = df["merged"].str.split("|", expand=True)

    # Pad if fewer columns than expected, trim if more
    for i in range(split.shape[1], n_fields):
        split[i] = ""
    split = split.iloc[:, :n_fields]
    split.columns = fields

    # Strip whitespace from all string columns at once
    split = split.apply(lambda col: col.str.strip())

    # Combine with any extra columns from the original CSV (besides "merged")
    extra_cols = [c for c in df.columns if c != "merged"]
    if extra_cols:
        out = pd.concat([df[extra_cols], split], axis=1)
    else:
        out = split

    # Type conversions
    for col in schema["numeric"]:
        if col in out.columns:
            out[col] = pd.to_numeric(out[col], errors="coerce")

    out["block_time"] = pd.to_datetime(out["block_time"], errors="coerce")

    print(f"[{schema_name}] Saving: {output_file}")
    out.to_csv(output_file, index=False)
    print(f"[{schema_name}] Done — {len(out):,} rows written.")


def default_output(input_file):
    base, ext = os.path.splitext(input_file)
    return f"{base}_parsed{ext}"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Parse merged-column Dune exports into clean CSVs."
    )
    parser.add_argument(
        "type", choices=SCHEMAS.keys(),
        help="Schema type: 'txs' for DEX trades, 'reverts' for all txs with success flag",
    )
    parser.add_argument("input_file", help="Path to input CSV with merged column")
    parser.add_argument(
        "output_file", nargs="?", default=None,
        help="Path to output CSV (default: <input>_parsed.csv)",
    )
    args = parser.parse_args()

    output = args.output_file or default_output(args.input_file)
    parse_merged(args.input_file, output, args.type)
